name: lint-js-ts
description: Setup Node.js and restore cached node_modules

runs:
  using:
    composite
    # lint:
    # runs-on: ubuntu-latest
    # needs: [type-check]
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   - name: Setup node and npm
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: "18"
    #   - name: Get node modules from cache
    #     uses: actions/cache@v3
    #     with:
    #       path: ./node_modules
    #       key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
    #   - name: Run eslint
    #     run: |
    #       mkdir -p /tmp/test-results;
    #       npx eslint .
  steps:
