name: setup-node
description: Setup Node.js and restore cached node_modules

inputs:
  NPM_TOKEN:
    description: Auth token for private npm packages
    required: true
  NPM_INSTALL_ENV:
    description: |
      Environment for running npm install. Pass in any value other than `production`
      to allow devDependencies to be installed.
    required: true

runs:
  using: composite
  steps:
    - name: Setup node and npm
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Cache node modules
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies on cache miss
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo ${{ inputs.NPM_TOKEN }}
        npm config set //registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}
        NODE_ENV=${{ inputs.NPM_INSTALL_ENV }} npm install --force
