name: setup-node
description: Setup Node.js and restore cached node_modules

inputs:
  NPM_TOKEN:
    description: Auth token for private npm packages
    required: true

runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Set npm access token
      shell: bash
      run: npm config set //registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: latest
        run_install: false

    - name: Get pnpm store directory
      id: directory
      shell: bash
      run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.directory.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: NODE_ENV=development pnpm install --ignore-scripts
